### ISSUE TITLE
backend equivlent 

### ISSUE THREAD

**Issue by gregbenner** [github/webauthn-json#19]
Hi there,
Is there a companion webauth json for the server side or a tutorial you could recommend?

**Comment by lgarron** [comment]
Hi @gregbenner, the server side will depend a lot on your language or framework. For example, we use https://github.com/cedarcode/webauthn-ruby because the frontend for github.com is written in Ruby, and that library can produce JSOn that can be used directly by `webauthn-json`. https://github.com/topics/webauthn might lead you to popular libraries in other languages.

https://webauthn.guide/ is a good general guide about how WebAuthn works.

Unfortunately, doing anything on the server side is out of scope for this library, so I'll close this issue for now.
