### ISSUE TITLE
Typescript 4.9.4: Types of property 'authenticatorAttachment' are incompatible

### ISSUE THREAD

**Issue by uwolfer** [github/webauthn-json#73]
With Typescript 4.9.4,  I am getting the following error. With TS 4.8.4, no such error is thrown.
```
node_modules/@github/webauthn-json/dist/types/basic/json.d.ts:9:18 - error TS2430: Interface 'PublicKeyCredentialWithClientExtensionResults' incorrectly extends interface 'PublicKeyCredential'.
  Types of property 'authenticatorAttachment' are incompatible.
    Type 'string | null | undefined' is not assignable to type 'string | null'.
      Type 'undefined' is not assignable to type 'string | null'.

```

**Comment by lgarron** [comment]
Thanks for the report! Unfortunately, this is a recurring problem with a living spec and multiple browser implementations.

In particular, it seems `authenticatorAttachment` is *not* available in Firefox 109, and I can't even find a bug for it: https://bugzilla.mozilla.org/buglist.cgi?quicksearch=authenticatorAttachment

It seems our options are:

1. Make `PublicKeyCredentialWithClientExtensionResults` extend `Omit<PublicKeyCredential, "authenticatorAttachment">` instead of `PublicKeyCredential`.
2. Publish a package with types that are incompatible with Firefox.

The latter is probably the least surprising, but it makes me very cranky about the health of the web platform.
